# Generated by Django 6.0.7 on 2026-08-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_is_published_remove_blog_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
